name: Build Godot Project

on:
  # all branches
  push:
    branches:
      - main
      - MG-AutomatedBuilds
  # pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: WizardBubbles
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "ggj2025"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}